[2023-05-04T13:43:15.669+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-04T13:43:15.703+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-04T13:43:15.704+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T13:43:15.706+0000] {taskinstance.py:1280} INFO - Starting attempt 5 of 6
[2023-05-04T13:43:15.706+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T13:43:15.734+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_dado> on 2023-05-03 00:00:00+00:00
[2023-05-04T13:43:15.741+0000] {standard_task_runner.py:55} INFO - Started process 367 to run task
[2023-05-04T13:43:15.747+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'ingest_dado', 'scheduled__2023-05-03T00:00:00+00:00', '--job-id', '735', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpfcnyej3i']
[2023-05-04T13:43:15.751+0000] {standard_task_runner.py:83} INFO - Job 735: Subtask ingest_dado
[2023-05-04T13:43:15.949+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-03T00:00:00+00:00 [running]> on host 43ca0f57de8c
[2023-05-04T13:43:16.100+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=ingest_dado
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-03T00:00:00+00:00
[2023-05-04T13:43:20.859+0000] {logging_mixin.py:137} INFO - Table(TableReference(DatasetReference('semiotic-joy-379201', 'venda'), 'tb_vendas'))
[2023-05-04T13:43:20.861+0000] {logging_mixin.py:137} INFO - [{'name': 'ID_MARCA', 'type': 'INTEGER'}, {'name': 'MARCA', 'type': 'STRING'}, {'name': 'ID_LINHA', 'type': 'INTEGER'}, {'name': 'LINHA', 'type': 'STRING'}, {'name': 'DATA_VENDA', 'type': 'DATE'}, {'name': 'QTD_VENDA', 'type': 'INTEGER'}]
[2023-05-04T13:43:22.332+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 50, in ingest_dados
    df = pd.read_excel(f"gs://bucket_raw_jr/input/Base 2017.xlsx")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1192, in __init__
    content_or_path=path_or_buffer, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1071, in inspect_excel_format
    content_or_path, "rb", storage_options=storage_options, is_text=False
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 359, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 134, in open
    return self.__enter__()
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 102, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/spec.py", line 1141, in open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 1323, in _open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 1479, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/spec.py", line 1491, in __init__
    self.size = self.details["size"]
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 1507, in details
    self._details = self.fs.info(self.path, generation=self.generation)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 798, in _info
    out = await self._ls(path, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 836, in _ls
    path, prefix=prefix, versions=versions
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 549, in _list_objects
    return [await self._get_object(path)]
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 492, in _get_object
    "GET", "b/{}/o/{}", bucket, key, json_out=True, generation=generation
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 419, in _call
    method, path, *args, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/decorator.py", line 221, in fun
    return await caller(func, *(extras + args), **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/retry.py", line 114, in retry_request
    return await func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/core.py", line 411, in _request
    validate_response(status, contents, path, args)
  File "/home/airflow/.local/lib/python3.7/site-packages/gcsfs/retry.py", line 83, in validate_response
    raise FileNotFoundError(path)
FileNotFoundError: b/bucket_raw_jr/o/input%2FBase%202017.xlsx
[2023-05-04T13:43:22.397+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gsc_to_bq, task_id=ingest_dado, execution_date=20230503T000000, start_date=20230504T134315, end_date=20230504T134322
[2023-05-04T13:43:22.440+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 735 for task ingest_dado (b/bucket_raw_jr/o/input%2FBase%202017.xlsx; 367)
[2023-05-04T13:43:22.489+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-04T13:43:22.545+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
