[2023-03-05T02:49:31.053+0000] {taskinstance.py:1077} INFO - Dependencies not met for <TaskInstance: teste_dag.captura_dados scheduled__2023-03-05T01:30:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2023-03-05T02:49:31.061+0000] {local_task_job.py:147} INFO - Task is not able to be run
