[2023-04-26T18:10:55.957+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.create_bucket_raw scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-04-26T18:10:56.035+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.create_bucket_raw scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2023-04-26T18:10:56.057+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:10:56.073+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-04-26T18:10:56.073+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:10:56.177+0000] {taskinstance.py:1300} INFO - Executing <Task(GCSCreateBucketOperator): create_bucket_raw> on 2023-04-23 00:00:00+00:00
[2023-04-26T18:10:56.260+0000] {standard_task_runner.py:55} INFO - Started process 660 to run task
[2023-04-26T18:10:56.287+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'create_bucket_raw', 'scheduled__2023-04-23T00:00:00+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpx1o7wbeu']
[2023-04-26T18:10:56.295+0000] {standard_task_runner.py:83} INFO - Job 350: Subtask create_bucket_raw
[2023-04-26T18:10:56.943+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.create_bucket_raw scheduled__2023-04-23T00:00:00+00:00 [running]> on host ec729a0ad77f
[2023-04-26T18:10:57.441+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=create_bucket_raw
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-23T00:00:00+00:00
[2023-04-26T18:10:57.530+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-04-26T18:10:57.661+0000] {gcs.py:880} INFO - Creating Bucket: bucket_raw; Location: us-central1; Storage Class: STANDARD
[2023-04-26T18:10:59.386+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 158, in execute
    labels=self.labels,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 897, in create_bucket
    bucket.create(project=project_id, location=location)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 989, in create
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 954, in create_bucket
    _target_object=bucket,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 620, in _post_resource
    _target_object=_target_object,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://storage.googleapis.com/storage/v1/b?project=semiotic-joy-379201&prettyPrint=false: gcs-to-bq@semiotic-joy-379201.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not exist).
[2023-04-26T18:10:59.490+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=gsc_to_bq, task_id=create_bucket_raw, execution_date=20230423T000000, start_date=20230426T181055, end_date=20230426T181059
[2023-04-26T18:10:59.578+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 350 for task create_bucket_raw (403 POST https://storage.googleapis.com/storage/v1/b?project=semiotic-joy-379201&prettyPrint=false: gcs-to-bq@semiotic-joy-379201.iam.gserviceaccount.com does not have storage.buckets.create access to the Google Cloud project. Permission 'storage.buckets.create' denied on resource (or it may not exist).; 660)
[2023-04-26T18:10:59.677+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-26T18:10:59.826+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
