[2023-05-03T03:16:37.532+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T03:16:37.591+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T03:16:37.594+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T03:16:37.603+0000] {taskinstance.py:1280} INFO - Starting attempt 11 of 11
[2023-05-03T03:16:37.611+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T03:16:37.684+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_dado> on 2023-05-02 00:00:00+00:00
[2023-05-03T03:16:37.710+0000] {standard_task_runner.py:55} INFO - Started process 443 to run task
[2023-05-03T03:16:37.720+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'ingest_dado', 'scheduled__2023-05-02T00:00:00+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmp9ok0rr53']
[2023-05-03T03:16:37.730+0000] {standard_task_runner.py:83} INFO - Job 615: Subtask ingest_dado
[2023-05-03T03:16:38.131+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [running]> on host 63f59780fc7a
[2023-05-03T03:16:38.602+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=ingest_dado
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=11
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-02T00:00:00+00:00
[2023-05-03T03:16:42.000+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 25, in ingest_dados
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-05-03T03:16:42.392+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=gsc_to_bq, task_id=ingest_dado, execution_date=20230502T000000, start_date=20230503T031637, end_date=20230503T031642
[2023-05-03T03:16:42.682+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 615 for task ingest_dado (No module named 'gspread'; 443)
[2023-05-03T03:16:43.084+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-03T03:16:43.350+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
