[2023-05-03T13:18:05.679+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T13:18:05.707+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T13:18:05.709+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T13:18:05.710+0000] {taskinstance.py:1280} INFO - Starting attempt 26 of 27
[2023-05-03T13:18:05.710+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T13:18:05.753+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_dado> on 2023-05-02 00:00:00+00:00
[2023-05-03T13:18:05.768+0000] {standard_task_runner.py:55} INFO - Started process 497 to run task
[2023-05-03T13:18:05.776+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'ingest_dado', 'scheduled__2023-05-02T00:00:00+00:00', '--job-id', '637', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpy9i6p288']
[2023-05-03T13:18:05.778+0000] {standard_task_runner.py:83} INFO - Job 637: Subtask ingest_dado
[2023-05-03T13:18:05.929+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [running]> on host 63f59780fc7a
[2023-05-03T13:18:06.150+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=ingest_dado
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=26
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-02T00:00:00+00:00
[2023-05-03T13:18:06.155+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 24, in ingest_dados
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2023-05-03T13:18:06.193+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gsc_to_bq, task_id=ingest_dado, execution_date=20230502T000000, start_date=20230503T131805, end_date=20230503T131806
[2023-05-03T13:18:06.216+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 637 for task ingest_dado (No module named 'gspread'; 497)
[2023-05-03T13:18:06.268+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-03T13:18:06.328+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
